name: Deploy Tutor Service
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Debug Build Context
        run: ls -la src && ls -la src/Utils || echo "Utils folder missing"
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: jacksoncheriyan05/tutor-service:${{ steps.vars.outputs.sha_short }}
      
      - name: Debug container files
        run: docker run --rm jacksoncheriyan05/tutor-service:${{ steps.vars.outputs.sha_short }} ls -la /app
  
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Connect to Kubernetes cluster
        run: doctl kubernetes cluster kubeconfig save dowhilelearn-cluster

      - name: Update Kubernetes deployment
        run: |
          kubectl set image deployment/tutor-service tutor-service=jacksoncheriyan05/tutor-service:${{ steps.vars.outputs.sha_short }} -n dowhilelearn